name: Deployment

on:
  push:
    branches:
      - 'main'
    tags:
     - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      container_digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Setup the current date
        id: prep
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: marshallasch/automated-builder
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=tag
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/amd64/v2,linux/arm/v7,linux/arm/v6,linux/386
          build-args: |
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
