name: Verification

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable

  build-test:

    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        python-version: ['3.10', '3.9', '3.8', '3.7']
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          # mac os: exclude all but the last two python releases
          - os: macos-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.7
          # windows: exclude all but the last two python releases
          - os: windows-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.7

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python tools
      run: |
        python -m pip install --upgrade pip

    - name: Set up a environment to install into, and install the package from sources
      run: |
        python -m venv vinstall
        export PATH=vinstall/bin/:vinstall/Scripts/:$PATH
        python -m pip install .

    - name: Test that the installed executable is able to run
      run: |
        export PATH=vinstall/bin/:vinstall/Scripts/:$PATH
        scioer-builder --help